
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Dependencies and Clean Install
    init: |
      sdk use java 16.0.1.hs-adpt
      cd sultn; mvn clean install -DskipUiTests; cd ui;
      gp sync-done build
  - name: Springboot server
    init: gp sync-await build && cd sultn; cd springboot; mvn spring-boot:run;

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080

vscode:
  extensions:
    - ritwickdey.liveserver
    - jebbs.plantuml